In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from datetime import datetime
import glob
import json

In [10]:

!pip install patool

Collecting patool
  Downloading patool-1.15.0-py2.py3-none-any.whl (91 kB)
Installing collected packages: patool
Successfully installed patool-1.15.0

In [12]:
import patoolib
patoolib.extract_archive("Flight Data.zip",outdir="/content")

patool: Extracting Flight Data.zip ...
patool: running "C:\Program Files\7-Zip\7z.EXE" x -o/content -- "Flight Data.zip"
patool:     with creationflags=134217728
patool: ... Flight Data.zip extracted to `/content'.

'/content'

In [16]:
# import pyarrow.parquet as pq

# df = pq.read_table(source="/content").to_pandas()

In [19]:
import pandas as pd

# Specify the path to your Parquet file
parquet_file_path = '/content/Combined_Flights_2018.parquet'

# Use pandas to read the Parquet file
df = pd.read_parquet(parquet_file_path)

# Display the DataFrame
df.head(100)

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,...,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2018-01-23,Endeavor Air Inc.,ABY,ATL,False,False,1202,1157.0,0.0,-5.0,...,1211.0,1249.0,7.0,1304,-8.0,0.0,-1.0,1300-1359,1,0.0
1,2018-01-24,Endeavor Air Inc.,ABY,ATL,False,False,1202,1157.0,0.0,-5.0,...,1210.0,1246.0,12.0,1304,-6.0,0.0,-1.0,1300-1359,1,0.0
2,2018-01-25,Endeavor Air Inc.,ABY,ATL,False,False,1202,1153.0,0.0,-9.0,...,1211.0,1251.0,11.0,1304,-2.0,0.0,-1.0,1300-1359,1,0.0
3,2018-01-26,Endeavor Air Inc.,ABY,ATL,False,False,1202,1150.0,0.0,-12.0,...,1207.0,1242.0,11.0,1304,-11.0,0.0,-1.0,1300-1359,1,0.0
4,2018-01-27,Endeavor Air Inc.,ABY,ATL,False,False,1400,1355.0,0.0,-5.0,...,1412.0,1448.0,11.0,1500,-1.0,0.0,-1.0,1500-1559,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2018-01-06,Endeavor Air Inc.,LGA,SYR,False,False,1810,1805.0,0.0,-5.0,...,1825.0,1907.0,6.0,1928,-15.0,0.0,-1.0,1900-1959,1,0.0
96,2018-01-13,Endeavor Air Inc.,LGA,SYR,False,False,1810,1800.0,0.0,-10.0,...,1820.0,1901.0,6.0,1929,-22.0,0.0,-2.0,1900-1959,1,0.0
97,2018-01-14,Endeavor Air Inc.,LGA,SYR,False,False,1810,1803.0,0.0,-7.0,...,1832.0,1913.0,4.0,1931,-14.0,0.0,-1.0,1900-1959,1,0.0
98,2018-01-20,Endeavor Air Inc.,LGA,SYR,False,False,1810,1758.0,0.0,-12.0,...,1822.0,1857.0,6.0,1928,-25.0,0.0,-2.0,1900-1959,1,0.0
99,2018-01-27,Endeavor Air Inc.,LGA,SYR,False,False,1810,1758.0,0.0,-12.0,...,1822.0,1858.0,5.0,1929,-26.0,0.0,-2.0,1900-1959,1,0.0

In [20]:
import pandas as pd
import glob

# Specify the path pattern for your Parquet files
parquet_files_pattern = '/content/*.parquet'

# Use glob to get a list of file paths matching the pattern
parquet_file_paths = glob.glob(parquet_files_pattern)

# Initialize an empty DataFrame to store the combined data
combined_df = pd.DataFrame()

# Iterate through each Parquet file and append its content to the combined DataFrame
for file_path in parquet_file_paths:
    df = pd.read_parquet(file_path)
    combined_df = combined_df.append(df, ignore_index=True)

# Display the combined DataFrame
combined_df.desc

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,...,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2018-01-23,Endeavor Air Inc.,ABY,ATL,False,False,1202,1157.0,0.0,-5.0,...,1211.0,1249.0,7.0,1304,-8.0,0.0,-1.0,1300-1359,1,0.0
1,2018-01-24,Endeavor Air Inc.,ABY,ATL,False,False,1202,1157.0,0.0,-5.0,...,1210.0,1246.0,12.0,1304,-6.0,0.0,-1.0,1300-1359,1,0.0
2,2018-01-25,Endeavor Air Inc.,ABY,ATL,False,False,1202,1153.0,0.0,-9.0,...,1211.0,1251.0,11.0,1304,-2.0,0.0,-1.0,1300-1359,1,0.0
3,2018-01-26,Endeavor Air Inc.,ABY,ATL,False,False,1202,1150.0,0.0,-12.0,...,1207.0,1242.0,11.0,1304,-11.0,0.0,-1.0,1300-1359,1,0.0
4,2018-01-27,Endeavor Air Inc.,ABY,ATL,False,False,1400,1355.0,0.0,-5.0,...,1412.0,1448.0,11.0,1500,-1.0,0.0,-1.0,1500-1559,1,0.0

In [21]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29193782 entries, 0 to 29193781
Data columns (total 61 columns):
 #   Column                                   Dtype
---  ------                                   -----
 0   FlightDate                               datetime64[ns]
 1   Airline                                  object
 2   Origin                                   object
 3   Dest                                     object
 4   Cancelled                                bool
 5   Diverted                                 bool
 6   CRSDepTime                               int64
 7   DepTime                                  float64
 8   DepDelayMinutes                          float64
 9   DepDelay                                 float64
 10  ArrTime                                  float64
 11  ArrDelayMinutes                          float64
 12  AirTime                                  float64
 13  CRSElapsedTime                           float64
 14  ActualElapsedTime                        float64
 15  Distance                                 float64
 16  Year                                     int64
 17  Quarter                                  int64
 18  Month                                    int64
 19  DayofMonth                               int64
 20  DayOfWeek                                int64
 21  Marketing_Airline_Network                object
 22  Operated_or_Branded_Code_Share_Partners  object
 23  DOT_ID_Marketing_Airline                 int64
 24  IATA_Code_Marketing_Airline              object
 25  Flight_Number_Marketing_Airline          int64
 26  Operating_Airline                        object
 27  DOT_ID_Operating_Airline                 int64
 28  IATA_Code_Operating_Airline              object
 29  Tail_Number                              object
 30  Flight_Number_Operating_Airline          int64
 31  OriginAirportID                          int64
 32  OriginAirportSeqID                       int64
 33  OriginCityMarketID                       int64
 34  OriginCityName                           object
 35  OriginState                              object
 36  OriginStateFips                          int64
 37  OriginStateName                          object
 38  OriginWac                                int64
 39  DestAirportID                            int64
 40  DestAirportSeqID                         int64
 41  DestCityMarketID                         int64
 42  DestCityName                             object
 43  DestState                                object
 44  DestStateFips                            int64
 45  DestStateName                            object
 46  DestWac                                  int64
 47  DepDel15                                 float64
 48  DepartureDelayGroups                     float64
 49  DepTimeBlk                               object
 50  TaxiOut                                  float64
 51  WheelsOff                                float64
 52  WheelsOn                                 float64
 53  TaxiIn                                   float64
 54  CRSArrTime                               int64
 55  ArrDelay                                 float64
 56  ArrDel15                                 float64
 57  ArrivalDelayGroups                       float64
 58  ArrTimeBlk                               object
 59  DistanceGroup                            int64
 60  DivAirportLandings                       float64
dtypes: bool(2), datetime64[ns](1), float64(19), int64(22), object(17)
memory usage: 12.9+ GB

In [22]:
combined_df.to_parquet("final_flight_status.parquet", engine = "pyarrow")